### ISSUE TITLE
Usage with classic Sinatra style

### ISSUE THREAD

**Issue by khelll** [kalasjocke/sinatra-asset-pipeline#44]
I'm wondering if this can be used with the classic Sinatra style(not the classes/modules). Specially, the rake task also.

**Comment by kalasjocke** [comment]
If you can get hold of the app object in some way then yes, otherwise I would think it will get hard to define the rake task. Let me know if you find a solution.

**Comment by khelll** [comment]
There you go:
```ruby
Sinatra::AssetPipeline::Task.define! Sinatra::Application
```
That made things work smoothly, I could even integrate this with [Asset Async](https://github.com/rumblelabs/asset_sync) gem.

Please add the above to the documentation.

**Comment by kalasjocke** [comment]
@khelll Great stuff. I just added it to the readme: https://github.com/kalasjocke/sinatra-asset-pipeline/commit/94f68e2b3b055daff3913a2047f817569435fc61
