### ISSUE TITLE
Why assets_host works on production environment only?

### ISSUE THREAD

**Issue by khelll** [kalasjocke/sinatra-asset-pipeline#46]
This is making it hard to test on staging. I think this is already configurable since you give it a default value of `nil`, so why is it available in production only?

**Comment by kalasjocke** [comment]
No reason really. The staging and production environments should probably mirror each other as much as possible. Are you up for creating a pull request, or should I try to make it happen?

**Comment by kalasjocke** [comment]
Fixed.
