### ISSUE TITLE
Support for precompiling relative URL root

### ISSUE THREAD

**Issue by adamcrown** [kalasjocke/sinatra-asset-pipeline#48]
Any chance for supporting something like `rake assets:precompile RAILS_RELATIVE_URL_ROOT=/app` in Rails? I have an app I need to deploy not at the top level domain and can't seem to find a way to make it work with this gem.

**Comment by kalasjocke** [comment]
I haven't anything planned. But if you find time to implement it I would love a pull request.

**Comment by lgustafson** [comment]
In my experience doing something like the following in your configure block will help:

    configure do
      set :path_prefix, "/my-app"
    end

**Comment by kalasjocke** [comment]
After today the setting is called `assets_prefix` instead.
