### ISSUE TITLE
Sprockets 3.x support

### ISSUE THREAD

**Issue by brandonweiss** [kalasjocke/sinatra-asset-pipeline#51]
Is upgrading to Sprockets 3.x possible? There's some cool stuff like `sprockets-es6` that only works with 3.x.

**Comment by kalasjocke** [comment]
@brandonweiss I can't see why it's not. Have you tried making it happen or should I have a look at it?

**Comment by brandonweiss** [comment]
I didn't try. I don't know much about the internals of sprockets and since it was pessimistically locked to 2.x I assumed some changes would be necessary. Yeah, if you have time to to take a look that would be awesome :)

**Comment by kalasjocke** [comment]
@brandonweiss I'll try to make it happen then. :smile: Do you use this package over at Intercom btw?

**Comment by brandonweiss** [comment]
Thanks! No, it's just for something I'm playing around with. At Intercom, because of the type of app we're building it made sense to use Ember.js (or some thick client). So we're using Rails on the backend and Ember CLI on the frontend for asset pipelining.

**Comment by pkrefta** [comment]
I've done diggin into migration to Sprockets 3.x but this might be more complicated than expected because `sprockets-helpers' requires an update too.

**Comment by brandonweiss** [comment]
Yeah, I figured it might be. There is an [issue open](https://github.com/petebrowne/sprockets-helpers/issues/26) on `sprockets-helpers` but it's really old.

**Comment by kalasjocke** [comment]
@brandonweiss @pkrefta Thanks for looking into this, I haven't taken the time yet, sorry!

**Comment by dentarg** [comment]
Just FYI, looks like Sprockets 3.x support [has been added](https://github.com/petebrowne/sprockets-helpers/pull/29) to sprockets-helpers.

**Comment by kalasjocke** [comment]
@dentarg Great news! Lets make Sprockets 3.x support happen soon then.

**Comment by pkrefta** [comment]
@kalasjocke @dentarg I've added Sprockets 3.x support for sprockets-helpers but **sprockets-sass** needs some work too and it seems to be more complicated than expected because of internal Sprockets changes.

**Comment by bogdanRada** [comment]
+1

**Comment by musha68k** [comment]
+1

**Comment by dometto** [comment]
@pkrefta, could you please let us know if you're still planning to make this gem sprockets 3 compatible?

**Comment by bkoski** [comment]
As far as I can tell, this prevents use with any version of sinatra > 1.4.5 because of a tilt conflict.  When I try to install under sinatra 1.4.7 I get:

```
Resolving dependencies.................................
Bundler could not find compatible versions for gem "tilt":
  In snapshot (Gemfile.lock):
    tilt (= 2.0.2)

  In Gemfile:
    sinatra-asset-pipeline was resolved to 0.1.0, which depends on
      sinatra was resolved to 1.4.7, which depends on
        tilt (< 3, >= 1.3)

    sinatra-asset-pipeline was resolved to 0.1.0, which depends on
      sprockets-sass was resolved to 0.1.0, which depends on
        sprockets (~> 2.0) was resolved to 2.0.0, which depends on
          tilt (!= 1.3.0, ~> 1.1)

    sinatra-asset-pipeline was resolved to 0.1.0, which depends on
      sprockets-sass was resolved to 0.1.0, which depends on
        sprockets (~> 2.0) was resolved to 2.0.0, which depends on
          tilt (!= 1.3.0, ~> 1.1)
```

**Comment by bartkamphorst** [comment]
Thanks! 👍

**Comment by kalasjocke** [comment]
@bartkamphorst If you take it for a spin please let me know if everything works as expected.
