### ISSUE TITLE
Using absolute path in assets_prefix array

### ISSUE THREAD

**Issue by aluuu** [kalasjocke/sinatra-asset-pipeline#55]
Hello,

I've met a little problem with using absolute paths during `assets_prefix` configuration. 
```ruby
        app.assets_prefix.each do |prefix|
          paths = Dir[File.join(app.root, prefix, '*')]
          paths.each { |path| app.sprockets.append_path path }
        end
```
In case when absolute path was used, `paths` variable wouldn't be populated properly. 

What do you think, should this issue be fixed with detecting prefix to be absolute or not?

**Comment by kalasjocke** [comment]
Hi there @aluuu, sorry for not getting back to you in a very long time. Is this still an issue for you? 

It's a good question though. What's your use case for this? If you still think it's valid I would love a pull request to get it in. I'll close this issue for now, let's reopen we still think we should get this in.
