### ISSUE TITLE
Basic readme config doesn't generate any resources

### ISSUE THREAD

**Issue by stick** [kalasjocke/sinatra-asset-pipeline#61]
I've tried to follow the instructions in the README and none of my assets are being generated.

running the rake tasks also seems to do nothing, just generating an empty directory with an empty manifest file in it (just two curly brackets).

Both the js and css application files are pretty simple just a list of dependencies from bower, so I've added the bower directories with `assets_path` but again nothing is precompiled and nothing is served in development mode.

I'm probably doing something wrong but this was working pretty well but that was with 0.7.0.

Would appreciate any advice or help.

gist with my app.rb @ https://gist.github.com/stick/179bb9772b3a4d974bd76dc434cadb9c

**Comment by kalasjocke** [comment]
@stick Sorry to hear that. Did you find any luck over the last week or so? If not I'll try to have a look soon. Cheers!

**Comment by IanBurry** [comment]
I have the same problem as **@stick** above. Set it up according the README and basically, nothing happens. Rake task runs, but does not precompile, and nothing is served in dev mode

**Comment by kalasjocke** [comment]
@IanBurry That doesn't sounds good 🙁 Sorry that I haven't taken the time to look at this yet. If you do please send a pull request. Hopefully I can have a look at this soon.

**Comment by IanBurry** [comment]
Ok, I'm retracting my report.  I started tracing your code and saw that the asset paths weren't what I was expecting. If you want to have your asset directory structure mimic that of a rails app, you need to set :asset_paths appropriately. 

Upshot: the gem works fine, and is much easier than setting sprockets on its own. It just doesn't do all the magic for you :)

**Comment by kalasjocke** [comment]
@IanBurry Look at that. Perhaps it would be good idea to release a new major version to mimic the Rails behaviour. That's whats this gem is all about anyway 🙂 I guess both you and @stick expected that coming as new users to this gem. Do you think that would be a good change?

**Comment by stick** [comment]
I'm not running under rails (sinatra in my case) and I have asset_paths set (see the gist).  It's probably a good idea to have it mimic either the rails case or sinatra.

@IanBurry Can you put up a gist or something with what ended up working for you so I can possibly figure out what I'm doing wrong?

**Comment by IanBurry** [comment]
@kalasjocke That would have saved me an afternoon's thrashing about. Having it mimic Rails behavior out of the box is probably a good idea, but updating the README with a Rails-like example would be good enough.

@stick I put a bare-bones, classic style project here: [sinatra-asset-pipeline](https://github.com/IanBurry/sinatra-asset-pipeline)

**Comment by kalasjocke** [comment]
@IanBurry Sounds like two good suggestions. I'll make sure one of them happens. Thanks!
