### ISSUE TITLE
Assets not loaded

### ISSUE THREAD

**Issue by dimasjt** [kalasjocke/sinatra-asset-pipeline#63]
I'm just update gem from 0.7.0 to 1.0.x, the application.js and application.css is not loaded.
And when I try to precompile assets, the application.js and application.css is not in precompiled folder `public/assets/`

This is the error in console browser
`Refused to execute script from 'http://localhost:9292/javascripts/application.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

**Comment by kalasjocke** [comment]
Have you tried explicitly to set your `assets_paths` config parameter to `public/assets`? If not I think you should try that to see if it works. Sorry for nor making the migration path clearer.

**Comment by nuqz** [comment]
@dimasjt I believe that the last error happens because of `strict MIME type checking is enabled` in your client application (browser), but asset pipeline responds with `text/html` (much likely with 404 status code).
Try also to 'play' with `prefix` option:
```ruby
# Which prefix to serve the assets under
set :assets_prefix, 'custom-prefix' # default is assets: http://localhost:9292/assets/javascripts/...
```
