### ISSUE TITLE
Testing with Ruby 2.4, Sinatra 2.0 beta2, Rake, Sprockets gems also were updated

### ISSUE THREAD

**Issue by nuqz** [kalasjocke/sinatra-asset-pipeline#65]
Ruby was updated a month ago, Sinatra 2.0 is coming with Rack 2.0 features. It is time to prepare update too, isn't it? 😃

**Comment by kalasjocke** [comment]
@nuqz 👍 Let's have a discussion in #64.

**Comment by reicheltd** [comment]
any change to get this gem working with Sinatra 2.0?

**Comment by kalasjocke** [comment]
@reicheltd I'm happy to accept pull request. Perhaps we can continue where we started with #64? Would be cool to add a `prerelease` to test out 2.0 support.

**Comment by msalzburg** [comment]
@kalasjocke just gave this issue another try. Any thoughts?
