### ISSUE TITLE
Assets Doesn't load when upgraded from Ruby 1.9.3 to Ruby 2.4.3

### ISSUE THREAD

**Issue by Rajesh1213** [kalasjocke/sinatra-asset-pipeline#68]
Hi, 
I have a Sinatra application where I have upgraded from ruby 1.9.3 to ruby 2.4.3, after the upgrade assets are failing to load

`22:25:32 application.1 | 10.191.228.114 - - [25/Mar/2018:22:25:32 -0700] "GET /assets//stylesheets/sso.css HTTP/1.0" 404 9 0.0076`

`22:25:32 application.1 | 10.191.228.114 - - [25/Mar/2018:22:25:32 -0700] "GET /assets//javascripts/login.js HTTP/1.0" 404 9 0.0061`

`22:25:32 application.1 | 10.191.228.114 - - [25/Mar/2018:22:25:32 -0700] "GET /assets//javascripts/login.js HTTP/1.0" 404 9 0.0079`

Below is the code, please correct me if I am doing anything wrong here.
Javascripts and Stylesheets are in app/assets/  

````
require 'sinatra/base'
require 'sprockets'
require 'sprockets-helpers'
require 'sinatra/asset_pipeline'
require 'compass'

helpers Sprockets::Helpers

set :app_root, File.expand_path(File.dirname(__FILE__)+"/../../")
set :public_folder, File.join(app_root + "/public")
assets = %w(login.js sso.css *.png *.jpg *.gif views/invitations/signup_form.js)
locale_files = Dir[File.join(app_root, 'config', 'locales', '*.yml')]

set :scss,                  {:style => :compact, :debug_info => true}
set :assets_precompile,     assets
set :assets_paths,          %w(app/assets vendor/assets)
set :assets_prefix,         %w(app/assets vendor/assets)
set :assets_css_compressor, :sass
set :assets_js_compressor, :uglifier
set :session_secret, "something secret, something safe"

register Sinatra::AssetPipeline
````
NOTE: The same above configuration works perfectly fine with ruby 1.9.3

In Gemfile:
```
gem "sinatra", '~>1.4'
gem "sprockets", '~>3.6'
gem 'sprockets-helpers', '~>1.1'
gem 'sinatra-asset-pipeline', '~> 1.0.1'
gem 'uglifier'
gem 'sass', '~>3.4.22'
```

Thanks In Advance

**Comment by kalasjocke** [comment]
Thanks for reaching out. Since we're already discussing this issue over email I'll close this one for now. 

If anyone else finds this one I would suggest updating to the latest version of this gem if you're using ruby 2.x.
